version: 2
updates:
- package-ecosystem: cargo
  directory: "/donet"
  schedule:
    interval: daily
    time: "08:00"
    timezone: "America/Phoenix"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/libdonet"
  schedule:
    interval: daily
    time: "08:00"
    timezone: "America/Phoenix"
  open-pull-requests-limit: 10

