[package]
name = "donet"
version = "0.0.0"
edition = "2021"
license = "AGPL-3.0"
authors = ["maxrdz <me@maxrdz.com>"]
homepage = "https://github.com/donet-server/donet/"
repository = "https://github.com/donet-server/donet/"
keywords = ["donet", "dc", "networking", "panda3d", "server", "mmo"]
readme = "README.md"
publish = false

[dependencies]

