[package]
name = "pandanet"
version = "0.0.0"
edition = "2021"
license = "GPL-2.0"
authors = ["Max Rodriguez <max@vulkray.com>"]
homepage = "https://github.com/Max-Rodriguez/PandaNet/"
repository = "https://github.com/Max-Rodriguez/PandaNet/"
keywords = ["pandanet", "networking", "panda", "server", "otp", "mmo"]
readme = "README.md"
publish = false

[build]
jobs = 2
rustc = "rustc"
target = ["x86_64-unknown-linux-gnu", "i686-unknown-linux-gnu"]

[dependencies]
