[package]
name = "donetd"
version = "0.1.0"
edition = "2021"
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords = ["donet", "dc", "networking", "server", "mmo"]
readme = "README.md"
publish = false

[dependencies]
libdonet = { path = "../libdonet", version = "0.1.0", default-features = true }
tokio = { version = "1", features = ["rt-multi-thread", "net", "macros"] }
mysql = { version = "24.0", default-features = false, features = ["derive"] }
mysql_common = { version = "*", default-features = true }
serde = { version = "1", features = ["derive"] }
log = { version = "0.4", features = ["std"] }
toml = { version = "0.7" }
multimap = { version = "0.9" }
chrono = { version = "0.4" }