name: Build Workflow
on: [push, pull_request]

jobs:
  linux:
    name: Ubuntu
    timeout-minutes: 10
    env:
      DEBIAN_FRONTEND: "noninteractive"
    strategy:
      matrix:
        containers: [
          "rust:1.67.0",
          "rust:1.68.0",
          "rust:1.69.0",
          "rust:1.70.0",
          "rust:1.71.0",
          "rust:latest"
        ]
    runs-on: self-hosted
    container: ${{ matrix.containers }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Install Rust components
        run: |
          rustup component add rustfmt
          rustup component add clippy
      - name: Update System Packages
        run: |
          # Update package lists
          apt update -qq
          # Verify OpenSSL libraries are installed
          apt install -y libssl-dev
      - name: Print Rust compiler version
        run: rustc --version
      - name: Verify Rust code format
        run: cargo fmt --all -- --check
      - name: Run Unit Tests
        run: cargo test
      - name: Build DoNet debug
        run: cargo build
      - name: Build DoNet release
        run: cargo build --release
