name: Build Workflow
on: [push, pull_request]

jobs:
  linux:
    name: Ubuntu Linux
    timeout-minutes: 10
    env:
      DEBIAN_FRONTEND: "noninteractive"
      OPENSSL_DIR: "/usr/"
    strategy:
      matrix:
        rust-version: [
          "1.67.0",
          "1.68.0",
          "1.69.0",
          "1.70.0",
          "1.71.0",
          "latest"
        ]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Install Rust components
        run: |
          rustup component add rustfmt
          rustup component add clippy
          rustup target add i686-unknown-linux-gnu
      - name: Update System Packages
        run: |
          # Update package lists
          apt update -qq
          # Verify OpenSSL libraries are installed
          apt install -y libssl-dev
      - name: Print Rust compiler version
        run: rustc --version
      - name: Verify Rust code format
        run: cargo fmt --all -- --check
      - name: Run Unit Tests
        run: cargo test
      - name: Build DoNet debug
        run: cargo build
      - name: Build DoNet release
        run: cargo build --release
