name: Commit Naming
on: [push]

jobs:
  naming:
    name: Commit Naming
    runs-on: self-hosted
    steps:
      - uses: IceflowRE/gitcc@v2
        with:
          validator_file: .github/workflows/commit_check.mjs
